import { samsung02, samsung08, iphone, iphone01, iphone00, iphone02, iphone03
  , iphone08, iphone09, iphonex, samsung06, samsung04, iphone06, macbook1, hp1, hp5, macbook3, tablet3, watch2, tablet2, tablet8, airpod1, hp2, hp8, macbook4, tablet1, tablet6 } from "../../Assets"


export const productItems = [
    {
        id: 1,
        avatar: samsung02,
        name: "samsung ",
        category: "mobiles",
        brand: "samsung",
        copies: 5,
        review: "8 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        price: 300000,
        trend: "new",
        discount: "-10%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB",
        },
      },
      {
        id: 2,
        avatar: iphone00,
        name: "iphone",
        category: "mobiles",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "trend",
        price: 800000,
        trend: "hot",
        discount: "-9%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "256GB",
        },
      },
      {
        id: 3,
        avatar: iphone02,
        name: "iphone",
        category: "mobiles",
        brand: "apple",
        trend: "new",
        copies: 5,
        review: "8 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        price: 360000,
        discount: "-5%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB",
        },
      },
      {
        id: 4,
        avatar: iphonex,
        name: "iphone",
        category: "mobiles",
        brand: "apple",
        copies: 2,
        review: "3 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        price: 250000,
        trend: "hot",
        discount: "-10%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 5,
        avatar: iphone09,
        name: "iphone 13",
        category: "mobiles",
        brand: "apple",
        trend: "New",
        copies: 5,
        review: "7 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        price: 310000,
        discount: "-5%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 6,
        avatar: iphone,
        name: "Iphone 12",
        category: "mobiles",
        brand: "apple",
        copies: 5,
        review: "no review",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-4%",
        price: 200000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 7,
        avatar: iphone03,
        name: "iphone 14",
        category: "mobiles",
        brand: "apple",
        copies: 5,
        review: "1 review",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        trend: "new",
        discount: "-8%",
        price: 400000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 8,
        avatar: iphone08,
        name: "iphone",
        category: "mobiles",
        brand: "apple",
        copies: 3,
        review: "5 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-2%",
        price: 335000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 9,
        avatar: samsung08,
        name: "samsung",
        category: "mobiles",
        brand: "samsung",
        copies: 5,
        review: "9 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        price: 280000,
        discount: "-4%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 10,
        avatar: samsung06,
        name: "samsung",
        category: "",
        brand: "samsung",
        copies: 8,
        review: "2 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "trend",
        trend: "hot",
        price: 780000,
        discount: "-9%",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 11,
        avatar: samsung04,
        name: "samsung",
        category: "",
        brand: "samsung",
        copies: 5,
        review: "4 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-6%",
        price: 280000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 12,
        avatar: iphone01,
        name: "iphone",
        category: "",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        trend: "hot",
        discount: "-16%",
        price: 320000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 13,
        avatar: macbook1,
        name: "macbook pro",
        category: "laptops",
        brand: "apple",
        copies: 1,
        review: "5 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 870000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 14,
        avatar: hp1,
        name: "hp spectra",
        category: "laptops",
        brand: "hp",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        trend: "new",
        discount: "-16%",
        price: 320000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 15,
        avatar: tablet2,
        name: "ipad pro",
        category: "tablets",
        brand: "apple",
        copies: 3,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 510000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 16,
        avatar: watch2,
        name: "i-watch",
        category: "watch",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 120000,
        Delivery: "not free",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 17,
        avatar: tablet8,
        name: "ipad pro",
        category: "tablets",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 550000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 18,
        avatar: airpod1,
        name: "airpod",
        category: "airpods",
        brand: "apple",
        copies: 1,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 130000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 19,
        avatar: hp2,
        name: "hp",
        category: "laptops",
        brand: "hp",
        copies: 5,
        review: "1 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-3%",
        price: 275000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 20,
        avatar: hp8,
        name: "hp",
        category: "laptops",
        brand: "hp",
        copies: 3,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        trend: "hot",
        discount: "-16%",
        price: 230000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 21,
        avatar: macbook4,
        name: "mac pro",
        category: "laptops",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 930000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 22,
        avatar: iphone01,
        name: "iphone",
        category: "",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        trend: "hot",
        discount: "-16%",
        price: "320000",
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 23,
        avatar: tablet1,
        name: "ipad mini",
        category: "tablets",
        brand: "apple",
        copies: 5,
        review: "6 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "new",
        trend: "hot",
        discount: "-16%",
        price: 480000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
      {
        id: 24,
        avatar: tablet6,
        name: "ipad pro",
        category: "tablets",
        brand: "apple",
        copies: 5,
        review: "2 reviews",
        discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
        type: "hot",
        trend: "hot",
        discount: "-16%",
        price: 650000,
        Delivery: "Free Delivery",
        specs: {
          display: "5.8-inch Super Retina HD display",
          camera: "12MP dual cameras with dual OIS",
          battery: "Built-in rechargeable lithium-ion battery",
          storage: "64GB or 256GB",
        },
      },
 
]

export const popularProduct = [
  {
    id: 1,
    avatar: samsung02,
    name: "samsung",
    category: "mobiles",
    brand: "samsung",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 300000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 2,
    avatar: hp5,
    name: "hp",
    category: "laptops",
    brand: "hp",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 380000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 3,
    avatar: iphone08,
    name: "iphone 13",
    category: "mobiles",
    brand: "apple",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 280000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 4,
    avatar: iphone06,
    name: "iphone 12 ",
    category: "mobiles",
    brand: "samsung",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 430000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 5,
    avatar: samsung08,
    name: "samsung s20",
    category: "mobiles",
    brand: "samsung",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 380000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 6,
    avatar: macbook3,
    name: "macbook",
    category: "laptops",
    brand: "apple",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 850000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 7,
    avatar: tablet3,
    name: "ipad mini",
    category: "tablets",
    brand: "apple",
    copies: 2,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 490000,
    trend: "new",
    discount: "-10%",
    Delivery: "Free Delivery",
  },
  {
    id: 8,
    avatar: watch2,
    name: "i-watch",
    category: "mobiles",
    brand: "samsung",
    copies: 5,
    review: "8 reviews",
    discribe: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, nostrum",
    type: "new",
    price: 120000,
    trend: "new",
    discount: "-10%",
    Delivery: "not-free",
  },
]